### ISSUE TITLE
how to use  the func (g *Grapher) Comment(s string)

### ISSUE THREAD

**Issue by canghai908** [ziutek/rrd#17]
I use the func (g *Grapher) Comment(s string),but i found it not have wrap,I use g.Comment("\n") have no wrap,how can i do? I see the rrdtool sites is "/n".

**Comment by omani** [comment]
you need to escape the backlash in go.

try:
```
g.Comment("\\n")
```

**Comment by canghai908** [comment]
@omani Thanky you，I will try。
