### ISSUE TITLE
About display Align!

### ISSUE THREAD

**Issue by canghai908** [ziutek/rrd#21]
I use this rrd project,and I draw a pic like this:
![1](https://cloud.githubusercontent.com/assets/1450994/6705057/d5e96596-cd8b-11e4-9d1b-35a071b527bb.png)

How i can ailgn the display, like this.
![2](https://cloud.githubusercontent.com/assets/1450994/6705037/a5145412-cd8b-11e4-964c-62406af7eadd.png)

**Comment by ziutek** [comment]
This package is only simple binding to original rrd-tool. I don't know the answer to your question.
Please study rrd-tool documentation http://oss.oetiker.ch/rrdtool/doc/index.en.html You can ask your question to rrd-tool forum: http://oss.oetiker.ch/rrdtool/forum.en.html
